### ISSUE TITLE
It cannot running in windows

### ISSUE THREAD

**Issue by dreamingo88** [codeborne/play-tests#6]
The erros message:
`~ play! 1.5.x-localbuild, https://www.playframework.com
~
~ bash E:\v\play-1.5\modules\tests/gradle -b E:\v\play-1.5\modules\tests/build.gradle -p E:\v\play-1.5\hi -PPLAY_APP=E:\v\play-1.5\hi -PPLAY_HOME=E:\v\play-1.5 -Dfile.encoding=UTF-8 clean check test itest uitest combineUiTestResults -PUITEST_CLASS=ui/** -PTEST_COVERAGE_ENABLED=true
Traceback (most recent call last):
  File "E:\v\play-1.5\play", line 159, in <module>
    status = cmdloader.commands[play_command].execute(command=play_command, app=play_app, args=remaining_args, env=play_env, cmdloader=cmdloader)
  File "modules/tests\commands.py", line 104, in execute
    '-PUITEST_CLASS=%s' % uitest_class_pattern, '-PTEST_COVERAGE_ENABLED=%s' % test_coverage_enabled)
  File "modules/tests\commands.py", line 39, in execute_gradle
    return_code = subprocess.call(gradle_cmd, env=os.environ)
  File "E:\v\play-1.5\python\lib\subprocess.py", line 444, in call
    return Popen(*popenargs, **kwargs).wait()
  File "E:\v\play-1.5\python\lib\subprocess.py", line 595, in __init__
    errread, errwrite)
  File "E:\v\play-1.5\python\lib\subprocess.py", line 821, in _execute_child
    startupinfo)
WindowsError: [Error 2]`

Is there any way to use it in windows 10?

**Comment by asolntsev** [comment]
@dreamingo88 Are you sure it's `play-tests` specific problem?
Can you run any other play commands on Windows - for example, `play deps`?

**Comment by dreamingo88** [comment]
@asolntsev I just test it again, when run "play deps", it works. The message:
`E:\v\play-1.5\hi>..\play deps
~        _            _
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/
~
~ play! 1.5.x-localbuild, https://www.playframework.com
~
~ Resolving dependencies using E:\v\play-1.5\hi\conf\dependencies.yml,
~
~       play-codeborne->tests 8.14.1 (from codeborne)
~
~ Installing resolved dependencies,
~
~       modules/docviewer -> E:\v\play-1.5\modules\docviewer
~       modules/tests-8.14.1
~
~ Done!`


when run “play tests", it's wrong.  The erros message:
`E:\v\play-1.5\hi>..\play tests
~        _            _
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/
~
~ play! 1.5.x-localbuild, https://www.playframework.com
~
~ bash E:\v\play-1.5\hi\modules\tests-8.14.1/gradle -b E:\v\play-1.5\hi\modules\tests-8.14.1/build.gradle -p E:\v\play-1.5\hi -PPLAY_APP=E:\v\play-1.5\hi -PPLAY_HOME=E:\v\play-1.5 -Dfile.encoding=UTF-8 clean check test itest uitest combineUiTestResults -PUITEST_CLASS=ui/** -PTEST_COVERAGE_ENABLED=true
Traceback (most recent call last):
  File "E:\v\play-1.5\play", line 159, in <module>
    status = cmdloader.commands[play_command].execute(command=play_command, app=play_app, args=remaining_args, env=play_env, cmdloader=cmdloader)
  File "E:\v\play-1.5\hi\modules\tests-8.14.1\commands.py", line 104, in execute
    '-PUITEST_CLASS=%s' % uitest_class_pattern, '-PTEST_COVERAGE_ENABLED=%s' % test_coverage_enabled)
  File "E:\v\play-1.5\hi\modules\tests-8.14.1\commands.py", line 39, in execute_gradle
    return_code = subprocess.call(gradle_cmd, env=os.environ)
  File "E:\v\play-1.5\python\lib\subprocess.py", line 444, in call
    return Popen(*popenargs, **kwargs).wait()
  File "E:\v\play-1.5\python\lib\subprocess.py", line 595, in __init__
    errread, errwrite)
  File "E:\v\play-1.5\python\lib\subprocess.py", line 821, in _execute_child
    startupinfo)
WindowsError: [Error 2]`

Please check, thanks!
